import type { GateFacts } from './types.js';

/** Markdown pipes inside a value would split the cell and silently drop the rest of it. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

/**
 * The artifact both sides read: the author pastes it into the description, and the claims auditor
 * regenerates it and compares.
 *
 * Every row carries the command that produced it so a reviewer can spot-check any single number
 * without being told how, which is what keeps this from becoming a figure that is trusted because it
 * came from a script.
 */
export function formatFacts(facts: GateFacts): string {
  const lines: string[] = [
    '## Gate facts',
    '',
    `Generated by \`pnpm gate:facts\` for \`${facts.base}..${facts.head}\`. Regenerate it to check any row.`,
    '',
  ];

  for (const group of facts.groups) {
    lines.push(`### ${group.title}`, '', '| Fact | Value | Command |', '| --- | --- | --- |');
    for (const fact of group.facts) {
      const value = fact.failed ? `**${cell(fact.value)}**` : cell(fact.value);
      lines.push(`| ${cell(fact.key)} | ${value} | \`${cell(fact.command)}\` |`);
    }
    lines.push('');
  }

  if (facts.authorMeasured.length > 0) {
    lines.push(
      '### Author-measured, not reproduced',
      '',
      'Too slow for a reviewer to repeat. UNVERIFIABLE is the correct verdict on these, and reproducing one is a deliberate choice rather than the default.',
      '',
      '| Fact | Value | How it was measured |',
      '| --- | --- | --- |',
    );
    for (const measured of facts.authorMeasured) {
      lines.push(`| ${cell(measured.key)} | ${cell(measured.value)} | ${cell(measured.method)} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/** True when any collected fact failed, which is what the command's exit code reports. */
export function hasFailure(facts: GateFacts): boolean {
  return facts.groups.some((group) => group.facts.some((fact) => fact.failed));
}
