FROM node:20-alpine

WORKDIR /app

COPY packages/stream-uploader/package.json .
COPY packages/stream-uploader/dist/ ./dist/

# Install production dependencies only
RUN npm install --omit=dev

CMD ["node", "dist/index.js"]
