/**
 * Silencing exactly one rung of a live ladder, and nothing else.
 *
 * ## What a rung going quiet actually is
 *
 * SRS transcodes the ladder with **one ffmpeg process per rung**, generated by
 * `engines/srs/entrypoint.sh` from `ABR_LADDER`. Each one republishes to
 * `rtmp://127.0.0.1:PORT/[app]/[stream]_<rung>?vhost=<abr vhost>`, so the rung's name appears in its
 * own command line and nowhere else. That is the handle.
 *
 * ## ⛔ Why it is stopped rather than killed
 *
 * SRS supervises the processes it spawned and respawns one that exits, so a kill produces a rung that
 * is quiet for however long a respawn takes rather than for the window the run asked for. A stopped
 * process has not exited, so nothing respawns it, and the window is exactly the one the driver chose.
 * Same reasoning as `docker pause` over `docker stop` in the crash scenarios, one level down.
 *
 * ## ⛔ Why the whole command line is carried back
 *
 * A signal sent to the wrong process is invisible: three healthy rungs and one quiet one looks the
 * same whichever one was stopped, and a run that silenced nothing looks like a ladder that survived
 * the fault perfectly. The driver files what it matched so the artifact can be checked against what
 * it claims to have broken.
 */

import { shellQuoted } from '../harness/shellQuote.js';

/**
 * What the engine's own `require_rung_name` allows, restated.
 *
 * ⛔ Stricter than a general name: no underscore. The uploader recovers a rung by splitting the
 * stream id on its LAST underscore, so a rung carrying one cannot be matched back. A name that got
 * past this and into a shell would be a rung name deciding what command runs.
 */
const RUNG_NAME_RE = /^[A-Za-z0-9][A-Za-z0-9.-]*$/;

/** The signals this sends, and there are only two: quiet, and speaking again. */
export const SIGNAL_QUIET = 'STOP';
export const SIGNAL_RESUME = 'CONT';
type TranscodeSignal = typeof SIGNAL_QUIET | typeof SIGNAL_RESUME;

/** One rung's transcode process, as the container's own process table reports it. */
export interface RungProcess {
  pid: number;
  /** The whole command line, carried so the artifact can be checked against what was silenced. */
  args: string;
}

export function requireRungName(rung: string): string {
  if (!RUNG_NAME_RE.test(rung)) {
    throw new Error(
      `'${rung}' is not a rung name this can act on (expected ${RUNG_NAME_RE.source}). The engine's own ` +
        'require_rung_name applies the same rule, so a name that fails here would never have produced a rung.',
    );
  }
  return rung;
}

/**
 * The substring of a transcode's command line that identifies which rung it produces.
 *
 * ⛔ Includes the `?` that starts the vhost query, so `360p` cannot match a rung named `360px` and a
 * rung name that happens to be a prefix of another is unambiguous.
 */
export function rungOutputMarker(rung: string): string {
  return `_${requireRungName(rung)}?vhost=`;
}

/** Read the container's process table. Parsed here rather than filtered there, so it can be tested. */
export function listProcessesCommand(container: string): string {
  return `docker exec ${shellQuoted(container)} ps -eo pid,args`;
}

/**
 * The transcode processes producing one rung, out of a `ps -eo pid,args` table.
 *
 * Returns every match rather than the first. ⛔ More than one is a state the caller has to see: SRS
 * respawning around a previous run, or two broadcasts live at once, either of which makes a single
 * stopped process the wrong fault.
 */
export function rungProcesses(psOutput: string, rung: string): readonly RungProcess[] {
  const marker = rungOutputMarker(rung);

  return (
    psOutput
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line.includes(marker))
      // The header is `PID COMMAND` and cannot contain the marker, so only real rows reach here.
      .map((line) => {
        const separator = line.indexOf(' ');
        return { pid: Number(line.slice(0, separator)), args: line.slice(separator + 1).trim() };
      })
      .filter((process) => Number.isInteger(process.pid) && process.pid > 0)
  );
}

/**
 * Send one signal to a named set of pids inside a container.
 *
 * ⛔ By pid rather than by pattern. The pattern found them once, and re-matching to resume would
 * silence a process that started meanwhile, which is a second fault the run never chose.
 */
export function signalCommand(container: string, pids: readonly number[], signal: TranscodeSignal): string {
  if (pids.length === 0) {
    throw new Error(`nothing to send SIG${signal} to, so this would report success for a fault that never landed`);
  }
  const targets = pids.map((pid) => String(requirePid(pid))).join(' ');
  return `docker exec ${shellQuoted(container)} kill -${signal} ${targets}`;
}

function requirePid(pid: number): number {
  if (!Number.isInteger(pid) || pid <= 0) {
    throw new Error(`'${pid}' is not a pid. A signal is about to be sent, so this is not a value to guess at.`);
  }
  return pid;
}
